# Generated by Django 2.0.7 on 2018-10-30 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('afip', '0003_auto_20180821_1213'),
        ('clubes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('plazo', models.PositiveIntegerField(blank=True, null=True)),
                ('clase', models.CharField(choices=[('interes', 'Interes'), ('descuento', 'Descuento')], max_length=15)),
                ('tipo', models.CharField(choices=[('fijo', 'Monto fijo'), ('tasa', 'Tasa')], default='tasa', max_length=15)),
                ('monto', models.IntegerField(blank=True, null=True)),
                ('base_calculo', models.IntegerField(choices=[(1, 'Diario'), (7, 'Semanal'), (15, 'Quincenal'), (30, 'Mensual'), (60, 'Bimestral'), (90, 'Trimestral'), (120, 'Semestral')], default=30)),
                ('condicion', models.CharField(blank=True, choices=[(None, 'Sin condicion'), ('grupo', 'Pertenencia a un grupo familiar')], max_length=15, null=True)),
                ('finalizacion', models.DateField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Club')),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Acreedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primario', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=150)),
                ('numero_documento', models.CharField(blank=True, max_length=13, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Club')),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primario', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=30)),
                ('entidad', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Club')),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('edad_limite', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_limite', models.PositiveIntegerField(blank=True, null=True)),
                ('asignacion_automatica', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='clubes.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primario', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=30)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Club')),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primario', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=30)),
                ('prioritario', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Club')),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('fecha_nacimiento', models.DateField()),
                ('es_extranjero', models.BooleanField(default=False)),
                ('numero_documento', models.CharField(blank=True, max_length=13, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=100, null=True)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('profesion', models.CharField(blank=True, max_length=40, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='socios', to='parametros.Categoria')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Club')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubes.Codigo_Provincia')),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='afip.DocumentType')),
                ('usuarios', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['apellido'],
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='cabeza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='familia', to='parametros.Socio'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Club'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='socios',
            field=models.ManyToManyField(to='parametros.Socio'),
        ),
        migrations.AddField(
            model_name='acreedor',
            name='genera',
            field=models.ManyToManyField(blank=True, related_name='genera', to='parametros.Relacion'),
        ),
        migrations.AddField(
            model_name='acreedor',
            name='recibe',
            field=models.ManyToManyField(blank=True, related_name='recibe', to='parametros.Relacion'),
        ),
        migrations.AddField(
            model_name='acreedor',
            name='tipo',
            field=models.ManyToManyField(to='parametros.Gasto'),
        ),
        migrations.AddField(
            model_name='acreedor',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='afip.DocumentType'),
        ),
        migrations.AddField(
            model_name='accesorio',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parametros.Ingreso'),
        ),
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together={('club', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('club', 'nombre')},
        ),
    ]
