# Generated by Django 2.0.7 on 2018-11-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_auto_20181030_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorio',
            name='clase',
            field=models.CharField(choices=[('interes', 'Interes'), ('descuento', 'Descuento'), ('bonificacion', 'Bonificacion')], max_length=15),
        ),
    ]
