# Generated by Django 2.0.7 on 2018-11-16 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametros', '0004_auto_20181106_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='socio',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
