# Generated by Django 2.0.7 on 2018-11-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0005_auto_20181116_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='baja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
