# Generated by Django 2.0.7 on 2018-11-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0006_auto_20181118_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='codigo',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
