# Generated by Django 2.0.7 on 2018-11-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0007_socio_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorio',
            name='reconocimiento',
            field=models.IntegerField(choices=[(1, 'Diario'), (7, 'Semanal'), (15, 'Quincenal'), (30, 'Mensual'), (60, 'Bimestral'), (90, 'Trimestral'), (120, 'Semestral'), (360, 'Anual')], default=1),
        ),
        migrations.AlterField(
            model_name='accesorio',
            name='base_calculo',
            field=models.IntegerField(choices=[(1, 'Diario'), (7, 'Semanal'), (15, 'Quincenal'), (30, 'Mensual'), (60, 'Bimestral'), (90, 'Trimestral'), (120, 'Semestral'), (360, 'Anual')], default=30),
        ),
    ]
