# Generated by Django 2.0.7 on 2018-11-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0008_auto_20181124_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='numero',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
