# Generated by Django 2.0.7 on 2018-11-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0009_socio_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesorio',
            name='ingreso',
        ),
        migrations.AddField(
            model_name='accesorio',
            name='ingreso',
            field=models.ManyToManyField(blank=True, to='parametros.Ingreso'),
        ),
    ]
