# Generated by Django 2.0.7 on 2018-11-30 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0010_auto_20181130_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='siguiente_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoria_anterior', to='parametros.Categoria'),
        ),
    ]
