# Generated by Django 2.0.7 on 2018-11-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0011_categoria_siguiente_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='baja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
