# Generated by Django 2.0.7 on 2019-01-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0013_socio_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='fecha_de_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
