# Generated by Django 2.0.3 on 2020-05-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0014_socio_fecha_de_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='inactivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='inactivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
