# Generated by Django 2.0.7 on 2019-01-10 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afip', '0003_auto_20180821_1213'),
        ('clubes', '0002_club_costo_mp'),
        ('parametros', '0014_socio_fecha_de_ingreso'),
        ('contabilidad', '0001_initial'),
        ('herramientas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaTransferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=10, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Club')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_destino', to='parametros.Caja')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_origen', to='parametros.Caja')),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='transferencias/pdf/')),
                ('asiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.Asiento')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Club')),
                ('punto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='afip.PointOfSales')),
            ],
        ),
        migrations.AddField(
            model_name='cajatransferencia',
            name='transferencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='herramientas.Transferencia'),
        ),
    ]
