# Generated by Django 2.0.7 on 2018-10-30 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CajaOP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(blank=True, max_length=10, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateField(auto_now=True)),
                ('fecha', models.DateField()),
                ('numero', models.CharField(blank=True, max_length=15, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('pagado', models.BooleanField(default=False)),
                ('aceptado', models.BooleanField(default=True)),
                ('anulado', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeudaOP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GastoDeuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GastoOP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('aceptado', models.BooleanField(default=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='op/pdf/')),
                ('anulado', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetencionOP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='op.Deuda')),
                ('op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='op.OP')),
            ],
        ),
    ]
