# Generated by Django 2.0.7 on 2018-10-30 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('op', '0001_initial'),
        ('afip', '0003_auto_20180821_1213'),
        ('parametros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0001_initial'),
        ('clubes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='op',
            name='acreedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Acreedor'),
        ),
        migrations.AddField(
            model_name='op',
            name='asiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asiento_op', to='contabilidad.Asiento'),
        ),
        migrations.AddField(
            model_name='op',
            name='asiento_anulado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asiento_op_anulado', to='contabilidad.Asiento'),
        ),
        migrations.AddField(
            model_name='op',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Club'),
        ),
        migrations.AddField(
            model_name='op',
            name='punto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afip.PointOfSales'),
        ),
        migrations.AddField(
            model_name='op',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gastoop',
            name='gasto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Gasto'),
        ),
        migrations.AddField(
            model_name='gastoop',
            name='op',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='op.OP'),
        ),
        migrations.AddField(
            model_name='gastodeuda',
            name='deuda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='op.Deuda'),
        ),
        migrations.AddField(
            model_name='gastodeuda',
            name='gasto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Gasto'),
        ),
        migrations.AddField(
            model_name='deudaop',
            name='deuda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='op.Deuda'),
        ),
        migrations.AddField(
            model_name='deudaop',
            name='op',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='op.OP'),
        ),
        migrations.AddField(
            model_name='deuda',
            name='acreedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Acreedor'),
        ),
        migrations.AddField(
            model_name='deuda',
            name='asiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asiento_deuda', to='contabilidad.Asiento'),
        ),
        migrations.AddField(
            model_name='deuda',
            name='asiento_anulado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asiento_deuda_anulado', to='contabilidad.Asiento'),
        ),
        migrations.AddField(
            model_name='deuda',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Club'),
        ),
        migrations.AddField(
            model_name='deuda',
            name='retencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametros.Relacion'),
        ),
        migrations.AddField(
            model_name='deuda',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cajaop',
            name='caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Caja'),
        ),
        migrations.AddField(
            model_name='cajaop',
            name='op',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='op.OP'),
        ),
    ]
