# Generated by Django 2.0.3 on 2020-05-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op', '0003_auto_20200509_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='op',
            name='fecha_operacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
