# Generated by Django 2.0.7 on 2018-11-07 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0004_auto_20181106_1835'),
        ('contabilidad', '0001_initial'),
        ('clubes', '0001_initial'),
        ('afip', '0003_auto_20180821_1213'),
        ('comprobantes', '0002_auto_20181030_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobante',
            name='confirmado',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='usuario',
        ),
        migrations.AddField(
            model_name='cajacomprobante',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clubes.Club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cajacomprobante',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cajacomprobante',
            name='socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametros.Socio'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='anulado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='asiento_anulado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asiento_comp_anulado', to='contabilidad.Asiento'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='nota_credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nota_de_credito', to='afip.Receipt'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='nota_debito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nota_de_debito', to='afip.Receipt'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='pdf_nota_credito',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/pdf/'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='pdf_nota_debito',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/pdf/'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='punto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='afip.PointOfSales'),
            preserve_default=False,
        ),
    ]
