# Generated by Django 2.0.7 on 2018-11-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0003_auto_20181107_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobante',
            name='pdf_nota_credito',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='pdf_nota_debito',
        ),
        migrations.AddField(
            model_name='comprobante',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
