# Generated by Django 2.0.7 on 2018-11-13 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0004_auto_20181112_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='punto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='afip.PointOfSales'),
        ),
    ]
