# Generated by Django 2.0.7 on 2018-11-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0005_auto_20181113_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajacomprobante',
            name='anulacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cobro',
            name='anulacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saldo',
            name='anulacion',
            field=models.BooleanField(default=False),
        ),
    ]
