# Generated by Django 2.0.7 on 2018-11-15 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0018_auto_20180808_1242'),
        ('comprobantes', '0006_auto_20181113_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobro',
            name='mercado_pago',
        ),
        migrations.AddField(
            model_name='cobro',
            name='preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mp.Preference'),
        ),
    ]
