# Generated by Django 2.0.7 on 2018-11-15 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0007_auto_20181115_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobro',
            name='preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mp.Preference'),
        ),
    ]
