# Generated by Django 2.0.3 on 2020-05-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='inactivo',
            field=models.BooleanField(default=False),
        ),
    ]
