# Generated by Django 2.0.7 on 2018-12-20 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0002_club_costo_mp'),
        ('reportes', '0002_auto_20181127_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cierre',
            name='liquidacion',
        ),
        migrations.RemoveField(
            model_name='cierre',
            name='per_cap',
        ),
        migrations.RemoveField(
            model_name='cierre',
            name='reservado',
        ),
        migrations.AddField(
            model_name='cierre',
            name='auditor',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='cierre',
            name='logo_auditor',
            field=models.ImageField(blank=True, null=True, upload_to='reportes/logos/'),
        ),
        migrations.AddField(
            model_name='cierre',
            name='mails',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reporte',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubes.Club'),
        ),
    ]
