# Generated by Django 2.0.7 on 2018-11-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0002_auto_20181030_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
