# Generated by Django 2.0.7 on 2018-11-03 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_auto_20181030_1309'),
        ('creditos', '0004_auto_20181102_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credito',
            name='accesorios',
        ),
        migrations.AddField(
            model_name='credito',
            name='acc_bonif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acc_bonif', to='parametros.Accesorio'),
        ),
        migrations.AddField(
            model_name='credito',
            name='acc_desc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acc_desc', to='parametros.Accesorio'),
        ),
        migrations.AddField(
            model_name='credito',
            name='acc_int',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acc_int', to='parametros.Accesorio'),
        ),
    ]
