# Generated by Django 2.0.7 on 2018-11-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0006_auto_20181103_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='mails',
            field=models.BooleanField(default=False),
        ),
    ]
